F7-Dark/Light-Mode-Toggle-Redux
georgedobrev/Building_Maintance pull request #11
Opened 2023-06-09 12:15 UTC by AntonioNik

![CurrentNavLightMode](https://github.com/georgedobrev/Building_Maintance/assets/131446929/53c88cb7-b3d2-4b33-b2e8-8d89c5c76525)
![CurrentNavDarkMode](https://github.com/georgedobrev/Building_Maintance/assets/131446929/9d795c9a-f1b1-42bf-a85e-34802cdbaecf)

2023-06-09 14:25 UTC, betinabp requested changes

2023-06-09 14:25 UTC, betinabp commented on Frontend/src/main.tsx
> +import "./main.css";
order the imports

2023-06-09 14:25 UTC, betinabp commented on Frontend/src/main.css
> +  background-color: #f1f1f1;
set variable for the colors

2023-06-09 14:25 UTC, betinabp commented on Frontend/src/components/navbar/Navbar.tsx
> +              <span style={{ marginRight: "12px" }}>
Use classes for styling. Avoid using inline styles.

2023-06-09 15:19 UTC, AntonioNik commented on Frontend/src/components/navbar/Navbar.tsx
> +              <span style={{ marginRight: "12px" }}>
in that case when I only need styles for one html tag should I create a scss file and import it to use it or there is a better approach

2023-06-12 06:33 UTC, betinabp commented on Frontend/src/components/navbar/Navbar.tsx
> +              <span style={{ marginRight: "12px" }}>
You can ceate a scss file. Stick to classes for styling

2023-06-12 06:35 UTC, betinabp requested changes

2023-06-12 06:35 UTC, betinabp commented on Frontend/src/pages/home/Home.tsx
> +const Home = () => {
Add type for Home. <img width="756" alt="image" src="https://github.com/georgedobrev/Restaurant_Assistant/assets/131862675/1a21de87-43c9-46c4-8748-16e7384d7e30">

2023-06-12 09:11 UTC, betinabp approved these changes

2023-06-12 09:11 UTC, merged