Added new Register forms for Add Manager and Add Building
georgedobrev/Building_Maintance pull request #31
Opened 2023-06-30 08:47 UTC by AntonioNik

Also the admiRegister is connected to the BE and creates an user, address and a building
![localhost_5173_register-admin (1)](https://github.com/georgedobrev/Building_Maintance/assets/131446929/97ed2be1-a284-4f52-a286-95e801e06e4b)
![localhost_5173_register-admin](https://github.com/georgedobrev/Building_Maintance/assets/131446929/de246730-19ff-431f-b446-445d40da2b9b)

2023-06-30 09:32 UTC, betinabp requested changes

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/store/users/userInterfaces.ts
> +export interface Address {
You can rename the file to `interfaces.ts`. It is clear that they are connected to the users since the parent folder is called `users`

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/users/Users.tsx
> +import { selectUsers } from "../../store/users/userSlice";
order the imports

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/users/Users.tsx
> +  id: number,
You should have interface for this.

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/register/AdminRegister.tsx
> +        const data = await fetchWrapper.get(api_all_countries);
Move this into a service file. You shouldn't call fetchWrapper from the components. Also this `const api_all_countries = "https://restcountries.com/v3.1/all";` should in a config.json file.

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/register/AdminRegister.tsx
> +      await fetchWrapper.post(
Same comment as above. Move this into a service file

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/register/AdminRegister.tsx
> +    console.log(building);
Remove the console log and address this comment `моля добавете си това правило в eslint-a https://eslint.org/docs/latest/rules/no-console`

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/services/authCalls.ts
> +import axios, { AxiosResponse } from 'axios';
Rename file to `authService`

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/addBuilding/AddBuilding.tsx
> +interface Country {
You have the same interface in 2 components. Move it in a common folder and reuse it.

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/addBuilding/AddBuilding.tsx
> +        const data = await fetchWrapper.get(api_all_countries);
Move this into a service file. You shouldn't call fetchWrapper from the components. Also this const api_all_countries = "https://restcountries.com/v3.1/all"; should in a config.json file.

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/addBuilding/AddBuilding.tsx
> +      const response = await fetchWrapper.post(
Move to service folder

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/addBuilding/AddBuilding.tsx
> +        "http://localhost:8086/building/create",
Create config.json file. The file should be a  object with baseUrl:  "http://localhost:8086", building: 'building'

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/addBuilding/AddBuilding.tsx
> +        "http://localhost:8086/building/create",
You shouldn't have any API URLs inside the components!

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/addBuilding/AddBuilding.tsx
> +    console.log(building);
remove

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/login/Login.tsx
> +    console.log(JSON.stringify(user));
remove

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/login/Login.tsx
> +      const response = await fetchWrapper.post(
move to authService file and call authService.login here

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/login/Login.tsx
> +      console.log(response);
remove

2023-06-30 09:32 UTC, betinabp commented on Frontend/src/pages/register/AdminRegister.tsx
> +interface Country {
Duplicated interface.

2023-07-02 13:49 UTC, betinabp requested changes

2023-07-02 13:49 UTC, betinabp commented on Frontend/src/pages/register/AdminRegister.tsx
> +    const fetchCountryNames = async () => {
Either directly execute the code from the 47th row to 57 or move the fetchCountryNames function outside of the useEffect. There is no point of declaring a function inside the useEffect and then executing it

2023-07-02 13:49 UTC, betinabp commented on Frontend/src/components/NotificationUI/NotificationCard.tsx
> +      }, 500);
Why this setTimeout is needed?

2023-07-03 07:54 UTC, betinabp requested changes

2023-07-03 07:54 UTC, betinabp commented on Frontend/src/pages/register/AdminRegister.tsx
> +  fetchCountryNames();
This should be wrapped around `useEffect`. What I meant in my previous comments was that you didn'y need to declare a function inside the useEffect.

2023-07-03 07:54 UTC, betinabp commented on Frontend/src/pages/addBuilding/AddBuilding.tsx
> +  fetchCountryNames();
Wrap this func inside useEffect

2023-07-03 07:54 UTC, betinabp commented on Frontend/src/pages/home/Home.tsx
>  const Home: React.FC<HomeProps> = ({ manager, currentUser }) => {
I don't see where in this component manager and currentUser are used. Please remove them and the interface if they are not needed.

2023-07-03 10:06 UTC, AntonioNik commented on Frontend/src/pages/home/Home.tsx
>  const Home: React.FC<HomeProps> = ({ manager, currentUser }) => {
manager and curr user will be used later on

2023-07-04 11:31 UTC, betinabp approved these changes

2023-07-04 11:31 UTC, merged